// Generated by cnn/pack_mobilenet_onchip.py; do not edit by hand.
// Body of the controller's case(layer_idx).
`ifdef SIGMA_MOBILENET_LAYER_CASE
8'd0: begin // features.0.0 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd1; layer_in_h <= 6'd28; layer_in_w <= 6'd28;
    layer_out_c <= 12'd8; layer_out_h <= 6'd14; layer_out_w <= 6'd14;
    layer_M <= 16'd196; layer_N <= 12'd8; layer_K <= 12'd10;
    layer_kernel <= 2'd3; layer_stride <= 2'd2; layer_pad <= 2'd1;
    weight_offset <= 19'd0;
    packed_weight_offset <= 19'd0;
    src_bank <= 2'd0; dst_bank <= 2'd1; skip_bank <= 2'd0;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd1: begin // features.1.conv.0.0 (depthwise)
    layer_kind <= 2'd1;
    layer_in_c <= 12'd8; layer_in_h <= 6'd14; layer_in_w <= 6'd14;
    layer_out_c <= 12'd8; layer_out_h <= 6'd14; layer_out_w <= 6'd14;
    layer_M <= 16'd196; layer_N <= 12'd8; layer_K <= 12'd10;
    layer_kernel <= 2'd3; layer_stride <= 2'd1; layer_pad <= 2'd1;
    weight_offset <= 19'd80;
    packed_weight_offset <= 19'd24;
    src_bank <= 2'd1; dst_bank <= 2'd0; skip_bank <= 2'd1;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd2: begin // features.1.conv.1 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd8; layer_in_h <= 6'd14; layer_in_w <= 6'd14;
    layer_out_c <= 12'd8; layer_out_h <= 6'd14; layer_out_w <= 6'd14;
    layer_M <= 16'd196; layer_N <= 12'd8; layer_K <= 12'd9;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd160;
    packed_weight_offset <= 19'd44;
    src_bank <= 2'd0; dst_bank <= 2'd2; skip_bank <= 2'd1;
    layer_relu6 <= 1'b0; layer_residual <= 1'b1;
end
8'd3: begin // features.2.conv.0.0 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd8; layer_in_h <= 6'd14; layer_in_w <= 6'd14;
    layer_out_c <= 12'd48; layer_out_h <= 6'd14; layer_out_w <= 6'd14;
    layer_M <= 16'd196; layer_N <= 12'd48; layer_K <= 12'd9;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd232;
    packed_weight_offset <= 19'd68;
    src_bank <= 2'd2; dst_bank <= 2'd0; skip_bank <= 2'd2;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd4: begin // features.2.conv.1.0 (depthwise)
    layer_kind <= 2'd1;
    layer_in_c <= 12'd48; layer_in_h <= 6'd14; layer_in_w <= 6'd14;
    layer_out_c <= 12'd48; layer_out_h <= 6'd7; layer_out_w <= 6'd7;
    layer_M <= 16'd49; layer_N <= 12'd48; layer_K <= 12'd10;
    layer_kernel <= 2'd3; layer_stride <= 2'd2; layer_pad <= 2'd1;
    weight_offset <= 19'd664;
    packed_weight_offset <= 19'd212;
    src_bank <= 2'd0; dst_bank <= 2'd1; skip_bank <= 2'd2;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd5: begin // features.2.conv.2 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd48; layer_in_h <= 6'd7; layer_in_w <= 6'd7;
    layer_out_c <= 12'd8; layer_out_h <= 6'd7; layer_out_w <= 6'd7;
    layer_M <= 16'd49; layer_N <= 12'd8; layer_K <= 12'd49;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd1144;
    packed_weight_offset <= 19'd332;
    src_bank <= 2'd1; dst_bank <= 2'd0; skip_bank <= 2'd2;
    layer_relu6 <= 1'b0; layer_residual <= 1'b0;
end
8'd6: begin // features.3.conv.0.0 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd8; layer_in_h <= 6'd7; layer_in_w <= 6'd7;
    layer_out_c <= 12'd48; layer_out_h <= 6'd7; layer_out_w <= 6'd7;
    layer_M <= 16'd49; layer_N <= 12'd48; layer_K <= 12'd9;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd1536;
    packed_weight_offset <= 19'd436;
    src_bank <= 2'd0; dst_bank <= 2'd1; skip_bank <= 2'd0;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd7: begin // features.3.conv.1.0 (depthwise)
    layer_kind <= 2'd1;
    layer_in_c <= 12'd48; layer_in_h <= 6'd7; layer_in_w <= 6'd7;
    layer_out_c <= 12'd48; layer_out_h <= 6'd7; layer_out_w <= 6'd7;
    layer_M <= 16'd49; layer_N <= 12'd48; layer_K <= 12'd10;
    layer_kernel <= 2'd3; layer_stride <= 2'd1; layer_pad <= 2'd1;
    weight_offset <= 19'd1968;
    packed_weight_offset <= 19'd580;
    src_bank <= 2'd1; dst_bank <= 2'd2; skip_bank <= 2'd0;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd8: begin // features.3.conv.2 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd48; layer_in_h <= 6'd7; layer_in_w <= 6'd7;
    layer_out_c <= 12'd8; layer_out_h <= 6'd7; layer_out_w <= 6'd7;
    layer_M <= 16'd49; layer_N <= 12'd8; layer_K <= 12'd49;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd2448;
    packed_weight_offset <= 19'd700;
    src_bank <= 2'd2; dst_bank <= 2'd1; skip_bank <= 2'd0;
    layer_relu6 <= 1'b0; layer_residual <= 1'b1;
end
8'd9: begin // features.4.conv.0.0 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd8; layer_in_h <= 6'd7; layer_in_w <= 6'd7;
    layer_out_c <= 12'd48; layer_out_h <= 6'd7; layer_out_w <= 6'd7;
    layer_M <= 16'd49; layer_N <= 12'd48; layer_K <= 12'd9;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd2840;
    packed_weight_offset <= 19'd804;
    src_bank <= 2'd1; dst_bank <= 2'd0; skip_bank <= 2'd1;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd10: begin // features.4.conv.1.0 (depthwise)
    layer_kind <= 2'd1;
    layer_in_c <= 12'd48; layer_in_h <= 6'd7; layer_in_w <= 6'd7;
    layer_out_c <= 12'd48; layer_out_h <= 6'd4; layer_out_w <= 6'd4;
    layer_M <= 16'd16; layer_N <= 12'd48; layer_K <= 12'd10;
    layer_kernel <= 2'd3; layer_stride <= 2'd2; layer_pad <= 2'd1;
    weight_offset <= 19'd3272;
    packed_weight_offset <= 19'd948;
    src_bank <= 2'd0; dst_bank <= 2'd1; skip_bank <= 2'd1;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd11: begin // features.4.conv.2 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd48; layer_in_h <= 6'd4; layer_in_w <= 6'd4;
    layer_out_c <= 12'd8; layer_out_h <= 6'd4; layer_out_w <= 6'd4;
    layer_M <= 16'd16; layer_N <= 12'd8; layer_K <= 12'd49;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd3752;
    packed_weight_offset <= 19'd1068;
    src_bank <= 2'd1; dst_bank <= 2'd0; skip_bank <= 2'd1;
    layer_relu6 <= 1'b0; layer_residual <= 1'b0;
end
8'd12: begin // features.5.conv.0.0 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd8; layer_in_h <= 6'd4; layer_in_w <= 6'd4;
    layer_out_c <= 12'd48; layer_out_h <= 6'd4; layer_out_w <= 6'd4;
    layer_M <= 16'd16; layer_N <= 12'd48; layer_K <= 12'd9;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd4144;
    packed_weight_offset <= 19'd1172;
    src_bank <= 2'd0; dst_bank <= 2'd1; skip_bank <= 2'd0;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd13: begin // features.5.conv.1.0 (depthwise)
    layer_kind <= 2'd1;
    layer_in_c <= 12'd48; layer_in_h <= 6'd4; layer_in_w <= 6'd4;
    layer_out_c <= 12'd48; layer_out_h <= 6'd4; layer_out_w <= 6'd4;
    layer_M <= 16'd16; layer_N <= 12'd48; layer_K <= 12'd10;
    layer_kernel <= 2'd3; layer_stride <= 2'd1; layer_pad <= 2'd1;
    weight_offset <= 19'd4576;
    packed_weight_offset <= 19'd1316;
    src_bank <= 2'd1; dst_bank <= 2'd2; skip_bank <= 2'd0;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd14: begin // features.5.conv.2 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd48; layer_in_h <= 6'd4; layer_in_w <= 6'd4;
    layer_out_c <= 12'd8; layer_out_h <= 6'd4; layer_out_w <= 6'd4;
    layer_M <= 16'd16; layer_N <= 12'd8; layer_K <= 12'd49;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd5056;
    packed_weight_offset <= 19'd1436;
    src_bank <= 2'd2; dst_bank <= 2'd1; skip_bank <= 2'd0;
    layer_relu6 <= 1'b0; layer_residual <= 1'b1;
end
8'd15: begin // features.6.conv.0.0 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd8; layer_in_h <= 6'd4; layer_in_w <= 6'd4;
    layer_out_c <= 12'd48; layer_out_h <= 6'd4; layer_out_w <= 6'd4;
    layer_M <= 16'd16; layer_N <= 12'd48; layer_K <= 12'd9;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd5448;
    packed_weight_offset <= 19'd1540;
    src_bank <= 2'd1; dst_bank <= 2'd0; skip_bank <= 2'd1;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd16: begin // features.6.conv.1.0 (depthwise)
    layer_kind <= 2'd1;
    layer_in_c <= 12'd48; layer_in_h <= 6'd4; layer_in_w <= 6'd4;
    layer_out_c <= 12'd48; layer_out_h <= 6'd4; layer_out_w <= 6'd4;
    layer_M <= 16'd16; layer_N <= 12'd48; layer_K <= 12'd10;
    layer_kernel <= 2'd3; layer_stride <= 2'd1; layer_pad <= 2'd1;
    weight_offset <= 19'd5880;
    packed_weight_offset <= 19'd1684;
    src_bank <= 2'd0; dst_bank <= 2'd2; skip_bank <= 2'd1;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd17: begin // features.6.conv.2 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd48; layer_in_h <= 6'd4; layer_in_w <= 6'd4;
    layer_out_c <= 12'd8; layer_out_h <= 6'd4; layer_out_w <= 6'd4;
    layer_M <= 16'd16; layer_N <= 12'd8; layer_K <= 12'd49;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd6360;
    packed_weight_offset <= 19'd1804;
    src_bank <= 2'd2; dst_bank <= 2'd0; skip_bank <= 2'd1;
    layer_relu6 <= 1'b0; layer_residual <= 1'b1;
end
8'd18: begin // features.7.conv.0.0 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd8; layer_in_h <= 6'd4; layer_in_w <= 6'd4;
    layer_out_c <= 12'd48; layer_out_h <= 6'd4; layer_out_w <= 6'd4;
    layer_M <= 16'd16; layer_N <= 12'd48; layer_K <= 12'd9;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd6752;
    packed_weight_offset <= 19'd1908;
    src_bank <= 2'd0; dst_bank <= 2'd1; skip_bank <= 2'd0;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd19: begin // features.7.conv.1.0 (depthwise)
    layer_kind <= 2'd1;
    layer_in_c <= 12'd48; layer_in_h <= 6'd4; layer_in_w <= 6'd4;
    layer_out_c <= 12'd48; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd48; layer_K <= 12'd10;
    layer_kernel <= 2'd3; layer_stride <= 2'd2; layer_pad <= 2'd1;
    weight_offset <= 19'd7184;
    packed_weight_offset <= 19'd2052;
    src_bank <= 2'd1; dst_bank <= 2'd0; skip_bank <= 2'd0;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd20: begin // features.7.conv.2 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd48; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd16; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd16; layer_K <= 12'd49;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd7664;
    packed_weight_offset <= 19'd2172;
    src_bank <= 2'd0; dst_bank <= 2'd1; skip_bank <= 2'd0;
    layer_relu6 <= 1'b0; layer_residual <= 1'b0;
end
8'd21: begin // features.8.conv.0.0 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd16; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd96; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd96; layer_K <= 12'd17;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd8448;
    packed_weight_offset <= 19'd2380;
    src_bank <= 2'd1; dst_bank <= 2'd0; skip_bank <= 2'd1;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd22: begin // features.8.conv.1.0 (depthwise)
    layer_kind <= 2'd1;
    layer_in_c <= 12'd96; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd96; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd96; layer_K <= 12'd10;
    layer_kernel <= 2'd3; layer_stride <= 2'd1; layer_pad <= 2'd1;
    weight_offset <= 19'd10080;
    packed_weight_offset <= 19'd2860;
    src_bank <= 2'd0; dst_bank <= 2'd2; skip_bank <= 2'd1;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd23: begin // features.8.conv.2 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd96; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd16; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd16; layer_K <= 12'd97;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd11040;
    packed_weight_offset <= 19'd3100;
    src_bank <= 2'd2; dst_bank <= 2'd0; skip_bank <= 2'd1;
    layer_relu6 <= 1'b0; layer_residual <= 1'b1;
end
8'd24: begin // features.9.conv.0.0 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd16; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd96; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd96; layer_K <= 12'd17;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd12592;
    packed_weight_offset <= 19'd3500;
    src_bank <= 2'd0; dst_bank <= 2'd1; skip_bank <= 2'd0;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd25: begin // features.9.conv.1.0 (depthwise)
    layer_kind <= 2'd1;
    layer_in_c <= 12'd96; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd96; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd96; layer_K <= 12'd10;
    layer_kernel <= 2'd3; layer_stride <= 2'd1; layer_pad <= 2'd1;
    weight_offset <= 19'd14224;
    packed_weight_offset <= 19'd3980;
    src_bank <= 2'd1; dst_bank <= 2'd2; skip_bank <= 2'd0;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd26: begin // features.9.conv.2 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd96; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd16; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd16; layer_K <= 12'd97;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd15184;
    packed_weight_offset <= 19'd4220;
    src_bank <= 2'd2; dst_bank <= 2'd1; skip_bank <= 2'd0;
    layer_relu6 <= 1'b0; layer_residual <= 1'b1;
end
8'd27: begin // features.10.conv.0.0 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd16; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd96; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd96; layer_K <= 12'd17;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd16736;
    packed_weight_offset <= 19'd4620;
    src_bank <= 2'd1; dst_bank <= 2'd0; skip_bank <= 2'd1;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd28: begin // features.10.conv.1.0 (depthwise)
    layer_kind <= 2'd1;
    layer_in_c <= 12'd96; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd96; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd96; layer_K <= 12'd10;
    layer_kernel <= 2'd3; layer_stride <= 2'd1; layer_pad <= 2'd1;
    weight_offset <= 19'd18368;
    packed_weight_offset <= 19'd5100;
    src_bank <= 2'd0; dst_bank <= 2'd2; skip_bank <= 2'd1;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd29: begin // features.10.conv.2 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd96; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd16; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd16; layer_K <= 12'd97;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd19328;
    packed_weight_offset <= 19'd5340;
    src_bank <= 2'd2; dst_bank <= 2'd0; skip_bank <= 2'd1;
    layer_relu6 <= 1'b0; layer_residual <= 1'b1;
end
8'd30: begin // features.11.conv.0.0 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd16; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd96; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd96; layer_K <= 12'd17;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd20880;
    packed_weight_offset <= 19'd5740;
    src_bank <= 2'd0; dst_bank <= 2'd1; skip_bank <= 2'd0;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd31: begin // features.11.conv.1.0 (depthwise)
    layer_kind <= 2'd1;
    layer_in_c <= 12'd96; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd96; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd96; layer_K <= 12'd10;
    layer_kernel <= 2'd3; layer_stride <= 2'd1; layer_pad <= 2'd1;
    weight_offset <= 19'd22512;
    packed_weight_offset <= 19'd6220;
    src_bank <= 2'd1; dst_bank <= 2'd0; skip_bank <= 2'd0;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd32: begin // features.11.conv.2 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd96; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd24; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd24; layer_K <= 12'd97;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd23472;
    packed_weight_offset <= 19'd6460;
    src_bank <= 2'd0; dst_bank <= 2'd1; skip_bank <= 2'd0;
    layer_relu6 <= 1'b0; layer_residual <= 1'b0;
end
8'd33: begin // features.12.conv.0.0 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd24; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd144; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd144; layer_K <= 12'd25;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd25800;
    packed_weight_offset <= 19'd7060;
    src_bank <= 2'd1; dst_bank <= 2'd0; skip_bank <= 2'd1;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd34: begin // features.12.conv.1.0 (depthwise)
    layer_kind <= 2'd1;
    layer_in_c <= 12'd144; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd144; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd144; layer_K <= 12'd10;
    layer_kernel <= 2'd3; layer_stride <= 2'd1; layer_pad <= 2'd1;
    weight_offset <= 19'd29400;
    packed_weight_offset <= 19'd8068;
    src_bank <= 2'd0; dst_bank <= 2'd2; skip_bank <= 2'd1;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd35: begin // features.12.conv.2 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd144; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd24; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd24; layer_K <= 12'd145;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd30840;
    packed_weight_offset <= 19'd8428;
    src_bank <= 2'd2; dst_bank <= 2'd0; skip_bank <= 2'd1;
    layer_relu6 <= 1'b0; layer_residual <= 1'b1;
end
8'd36: begin // features.13.conv.0.0 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd24; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd144; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd144; layer_K <= 12'd25;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd34320;
    packed_weight_offset <= 19'd9316;
    src_bank <= 2'd0; dst_bank <= 2'd1; skip_bank <= 2'd0;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd37: begin // features.13.conv.1.0 (depthwise)
    layer_kind <= 2'd1;
    layer_in_c <= 12'd144; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd144; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd144; layer_K <= 12'd10;
    layer_kernel <= 2'd3; layer_stride <= 2'd1; layer_pad <= 2'd1;
    weight_offset <= 19'd37920;
    packed_weight_offset <= 19'd10324;
    src_bank <= 2'd1; dst_bank <= 2'd2; skip_bank <= 2'd0;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd38: begin // features.13.conv.2 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd144; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd24; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd24; layer_K <= 12'd145;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd39360;
    packed_weight_offset <= 19'd10684;
    src_bank <= 2'd2; dst_bank <= 2'd1; skip_bank <= 2'd0;
    layer_relu6 <= 1'b0; layer_residual <= 1'b1;
end
8'd39: begin // features.14.conv.0.0 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd24; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd144; layer_out_h <= 6'd2; layer_out_w <= 6'd2;
    layer_M <= 16'd4; layer_N <= 12'd144; layer_K <= 12'd25;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd42840;
    packed_weight_offset <= 19'd11572;
    src_bank <= 2'd1; dst_bank <= 2'd0; skip_bank <= 2'd1;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd40: begin // features.14.conv.1.0 (depthwise)
    layer_kind <= 2'd1;
    layer_in_c <= 12'd144; layer_in_h <= 6'd2; layer_in_w <= 6'd2;
    layer_out_c <= 12'd144; layer_out_h <= 6'd1; layer_out_w <= 6'd1;
    layer_M <= 16'd1; layer_N <= 12'd144; layer_K <= 12'd10;
    layer_kernel <= 2'd3; layer_stride <= 2'd2; layer_pad <= 2'd1;
    weight_offset <= 19'd46440;
    packed_weight_offset <= 19'd12580;
    src_bank <= 2'd0; dst_bank <= 2'd1; skip_bank <= 2'd1;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd41: begin // features.14.conv.2 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd144; layer_in_h <= 6'd1; layer_in_w <= 6'd1;
    layer_out_c <= 12'd40; layer_out_h <= 6'd1; layer_out_w <= 6'd1;
    layer_M <= 16'd1; layer_N <= 12'd40; layer_K <= 12'd145;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd47880;
    packed_weight_offset <= 19'd12940;
    src_bank <= 2'd1; dst_bank <= 2'd0; skip_bank <= 2'd1;
    layer_relu6 <= 1'b0; layer_residual <= 1'b0;
end
8'd42: begin // features.15.conv.0.0 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd40; layer_in_h <= 6'd1; layer_in_w <= 6'd1;
    layer_out_c <= 12'd240; layer_out_h <= 6'd1; layer_out_w <= 6'd1;
    layer_M <= 16'd1; layer_N <= 12'd240; layer_K <= 12'd41;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd53680;
    packed_weight_offset <= 19'd14420;
    src_bank <= 2'd0; dst_bank <= 2'd1; skip_bank <= 2'd0;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd43: begin // features.15.conv.1.0 (depthwise)
    layer_kind <= 2'd1;
    layer_in_c <= 12'd240; layer_in_h <= 6'd1; layer_in_w <= 6'd1;
    layer_out_c <= 12'd240; layer_out_h <= 6'd1; layer_out_w <= 6'd1;
    layer_M <= 16'd1; layer_N <= 12'd240; layer_K <= 12'd10;
    layer_kernel <= 2'd3; layer_stride <= 2'd1; layer_pad <= 2'd1;
    weight_offset <= 19'd63520;
    packed_weight_offset <= 19'd17060;
    src_bank <= 2'd1; dst_bank <= 2'd2; skip_bank <= 2'd0;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd44: begin // features.15.conv.2 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd240; layer_in_h <= 6'd1; layer_in_w <= 6'd1;
    layer_out_c <= 12'd40; layer_out_h <= 6'd1; layer_out_w <= 6'd1;
    layer_M <= 16'd1; layer_N <= 12'd40; layer_K <= 12'd241;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd65920;
    packed_weight_offset <= 19'd17660;
    src_bank <= 2'd2; dst_bank <= 2'd1; skip_bank <= 2'd0;
    layer_relu6 <= 1'b0; layer_residual <= 1'b1;
end
8'd45: begin // features.16.conv.0.0 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd40; layer_in_h <= 6'd1; layer_in_w <= 6'd1;
    layer_out_c <= 12'd240; layer_out_h <= 6'd1; layer_out_w <= 6'd1;
    layer_M <= 16'd1; layer_N <= 12'd240; layer_K <= 12'd41;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd75560;
    packed_weight_offset <= 19'd20100;
    src_bank <= 2'd1; dst_bank <= 2'd0; skip_bank <= 2'd1;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd46: begin // features.16.conv.1.0 (depthwise)
    layer_kind <= 2'd1;
    layer_in_c <= 12'd240; layer_in_h <= 6'd1; layer_in_w <= 6'd1;
    layer_out_c <= 12'd240; layer_out_h <= 6'd1; layer_out_w <= 6'd1;
    layer_M <= 16'd1; layer_N <= 12'd240; layer_K <= 12'd10;
    layer_kernel <= 2'd3; layer_stride <= 2'd1; layer_pad <= 2'd1;
    weight_offset <= 19'd85400;
    packed_weight_offset <= 19'd22740;
    src_bank <= 2'd0; dst_bank <= 2'd2; skip_bank <= 2'd1;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd47: begin // features.16.conv.2 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd240; layer_in_h <= 6'd1; layer_in_w <= 6'd1;
    layer_out_c <= 12'd40; layer_out_h <= 6'd1; layer_out_w <= 6'd1;
    layer_M <= 16'd1; layer_N <= 12'd40; layer_K <= 12'd241;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd87800;
    packed_weight_offset <= 19'd23340;
    src_bank <= 2'd2; dst_bank <= 2'd0; skip_bank <= 2'd1;
    layer_relu6 <= 1'b0; layer_residual <= 1'b1;
end
8'd48: begin // features.17.conv.0.0 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd40; layer_in_h <= 6'd1; layer_in_w <= 6'd1;
    layer_out_c <= 12'd240; layer_out_h <= 6'd1; layer_out_w <= 6'd1;
    layer_M <= 16'd1; layer_N <= 12'd240; layer_K <= 12'd41;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd97440;
    packed_weight_offset <= 19'd25780;
    src_bank <= 2'd0; dst_bank <= 2'd1; skip_bank <= 2'd0;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd49: begin // features.17.conv.1.0 (depthwise)
    layer_kind <= 2'd1;
    layer_in_c <= 12'd240; layer_in_h <= 6'd1; layer_in_w <= 6'd1;
    layer_out_c <= 12'd240; layer_out_h <= 6'd1; layer_out_w <= 6'd1;
    layer_M <= 16'd1; layer_N <= 12'd240; layer_K <= 12'd10;
    layer_kernel <= 2'd3; layer_stride <= 2'd1; layer_pad <= 2'd1;
    weight_offset <= 19'd107280;
    packed_weight_offset <= 19'd28420;
    src_bank <= 2'd1; dst_bank <= 2'd0; skip_bank <= 2'd0;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd50: begin // features.17.conv.2 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd240; layer_in_h <= 6'd1; layer_in_w <= 6'd1;
    layer_out_c <= 12'd80; layer_out_h <= 6'd1; layer_out_w <= 6'd1;
    layer_M <= 16'd1; layer_N <= 12'd80; layer_K <= 12'd241;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd109680;
    packed_weight_offset <= 19'd29020;
    src_bank <= 2'd0; dst_bank <= 2'd1; skip_bank <= 2'd0;
    layer_relu6 <= 1'b0; layer_residual <= 1'b0;
end
8'd51: begin // features.18.0 (conv)
    layer_kind <= 2'd0;
    layer_in_c <= 12'd80; layer_in_h <= 6'd1; layer_in_w <= 6'd1;
    layer_out_c <= 12'd1280; layer_out_h <= 6'd1; layer_out_w <= 6'd1;
    layer_M <= 16'd1; layer_N <= 12'd1280; layer_K <= 12'd81;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd128960;
    packed_weight_offset <= 19'd33900;
    src_bank <= 2'd1; dst_bank <= 2'd0; skip_bank <= 2'd0;
    layer_relu6 <= 1'b1; layer_residual <= 1'b0;
end
8'd52: begin // classifier.1 (linear)
    layer_kind <= 2'd2;
    layer_in_c <= 12'd1280; layer_in_h <= 6'd1; layer_in_w <= 6'd1;
    layer_out_c <= 12'd10; layer_out_h <= 6'd1; layer_out_w <= 6'd1;
    layer_M <= 16'd1; layer_N <= 12'd10; layer_K <= 12'd1281;
    layer_kernel <= 2'd1; layer_stride <= 2'd1; layer_pad <= 2'd0;
    weight_offset <= 19'd232640;
    packed_weight_offset <= 19'd60780;
    src_bank <= 2'd0; dst_bank <= 2'd1; skip_bank <= 2'd0;
    layer_relu6 <= 1'b0; layer_residual <= 1'b0;
end
default: begin
    layer_kind <= 2'd2; layer_in_c <= 0; layer_in_h <= 0; layer_in_w <= 0;
    layer_out_c <= 0; layer_out_h <= 0; layer_out_w <= 0;
    layer_M <= 0; layer_N <= 0; layer_K <= 0;
    layer_kernel <= 0; layer_stride <= 0; layer_pad <= 0;
    weight_offset <= 0; packed_weight_offset <= 0; src_bank <= 0; dst_bank <= 0; skip_bank <= 0;
    layer_relu6 <= 0; layer_residual <= 0;
end
`endif
