#!/usr/bin/env python3
"""Fold BatchNorm and pack MobileNetV2-0.25 for the autonomous RTL top."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parents[2]
CNN_DIR = ROOT / "rtl" / "model"
VMOD_DIR = ROOT / "rtl" / "src"
sys.path.insert(0, str(CNN_DIR))

from mobilenet_onchip_model import DEFAULT_CHECKPOINT, extract_affine_ops, load_checkpoint


def bf16_words(values):
    values = np.asarray(values, dtype=np.float32)
    bits = values.view(np.uint32).copy()
    bits += np.uint32(0x7FFF) + ((bits >> 16) & 1)
    return (bits >> 16).astype(np.uint16)


def fold_batch_norm(conv, batch_norm):
    weight = conv.weight.detach().cpu().numpy().astype(np.float32)
    if conv.bias is None:
        bias = np.zeros(conv.out_channels, dtype=np.float32)
    else:
        bias = conv.bias.detach().cpu().numpy().astype(np.float32)
    if batch_norm is None:
        return weight, bias
    gamma = batch_norm.weight.detach().cpu().numpy().astype(np.float32)
    beta = batch_norm.bias.detach().cpu().numpy().astype(np.float32)
    mean = batch_norm.running_mean.detach().cpu().numpy().astype(np.float32)
    variance = batch_norm.running_var.detach().cpu().numpy().astype(np.float32)
    scale = gamma / np.sqrt(variance + np.float32(batch_norm.eps))
    reshape = (len(scale),) + (1,) * (weight.ndim - 1)
    return weight * scale.reshape(reshape), beta + (bias - mean) * scale


def packed_matrix(op):
    weight, bias = fold_batch_norm(op.module, op.batch_norm)
    if op.kind == "linear":
        matrix = weight.T
        return np.concatenate((matrix, bias[None, :]), axis=0)
    if op.kind == "depthwise":
        # One independent (kernel + bias) column per channel, contiguous by
        # channel so the RTL can issue N=1 grouped GEMMs without an index ROM.
        rows = []
        for channel in range(weight.shape[0]):
            rows.append(np.concatenate((weight[channel].reshape(-1), bias[channel:channel + 1])))
        return np.concatenate(rows)
    matrix = weight.reshape(weight.shape[0], -1).T
    return np.concatenate((matrix, bias[None, :]), axis=0)


def layer_metadata(index, op, offset, words, packed_offset, packed_rows, packed_layout):
    in_c, in_h, in_w = op.input_shape
    out_c, out_h, out_w = op.output_shape
    if op.kind == "linear":
        kernel = 1
        stride = 1
        padding = 0
        k_total = in_c + 1
        kind_code = 2
    else:
        kernel = int(op.module.kernel_size[0])
        stride = int(op.module.stride[0])
        padding = int(op.module.padding[0])
        k_total = (kernel * kernel * (1 if op.kind == "depthwise" else in_c)) + 1
        kind_code = 1 if op.kind == "depthwise" else 0
    return {
        "index": index,
        "name": op.name,
        "kind": op.kind,
        "kind_code": kind_code,
        "input": [in_c, in_h, in_w],
        "output": [out_c, out_h, out_w],
        "M": out_h * out_w,
        "N": out_c,
        "K_with_bias": k_total,
        "kernel": kernel,
        "stride": stride,
        "padding": padding,
        "weight_offset": offset,
        "weight_words": words,
        "packed_weight_offset": packed_offset,
        "packed_weight_rows": packed_rows,
        "packed_layout": packed_layout,
        "src_bank": op.src_bank,
        "dst_bank": op.dst_bank,
        "skip_bank": op.skip_bank,
        "relu6": op.activation == "relu6",
        "residual": op.residual,
    }


def emit_verilog_case(layers, output):
    lines = [
        "// Generated by cnn/pack_mobilenet_onchip.py; do not edit by hand.",
        "// Body of the controller's case(layer_idx).",
        "`ifdef SIGMA_MOBILENET_LAYER_CASE",
    ]
    for layer in layers:
        in_c, in_h, in_w = layer["input"]
        out_c, out_h, out_w = layer["output"]
        lines.extend([
            f"8'd{layer['index']}: begin // {layer['name']} ({layer['kind']})",
            f"    layer_kind <= 2'd{layer['kind_code']};",
            f"    layer_in_c <= 12'd{in_c}; layer_in_h <= 6'd{in_h}; layer_in_w <= 6'd{in_w};",
            f"    layer_out_c <= 12'd{out_c}; layer_out_h <= 6'd{out_h}; layer_out_w <= 6'd{out_w};",
            f"    layer_M <= 16'd{layer['M']}; layer_N <= 12'd{layer['N']}; layer_K <= 12'd{layer['K_with_bias']};",
            f"    layer_kernel <= 2'd{layer['kernel']}; layer_stride <= 2'd{layer['stride']}; layer_pad <= 2'd{layer['padding']};",
            f"    weight_offset <= 19'd{layer['weight_offset']};",
            f"    packed_weight_offset <= 19'd{layer['packed_weight_offset']};",
            f"    src_bank <= 2'd{layer['src_bank']}; dst_bank <= 2'd{layer['dst_bank']}; skip_bank <= 2'd{layer['skip_bank']};",
            f"    layer_relu6 <= 1'b{int(layer['relu6'])}; layer_residual <= 1'b{int(layer['residual'])};",
            "end",
        ])
    lines.extend([
        "default: begin",
        "    layer_kind <= 2'd2; layer_in_c <= 0; layer_in_h <= 0; layer_in_w <= 0;",
        "    layer_out_c <= 0; layer_out_h <= 0; layer_out_w <= 0;",
        "    layer_M <= 0; layer_N <= 0; layer_K <= 0;",
        "    layer_kernel <= 0; layer_stride <= 0; layer_pad <= 0;",
        "    weight_offset <= 0; packed_weight_offset <= 0; src_bank <= 0; dst_bank <= 0; skip_bank <= 0;",
        "    layer_relu6 <= 0; layer_residual <= 0;",
        "end",
        "`endif",
    ])
    output.write_text("\n".join(lines) + "\n", encoding="ascii")


def main():
    parser = argparse.ArgumentParser(description="Pack MobileNetV2-0.25 MNIST for SIGMA")
    parser.add_argument("--checkpoint", type=Path, default=DEFAULT_CHECKPOINT)
    parser.add_argument("--weights", type=Path, default=CNN_DIR / "mobilenet_onchip_bf16.mem")
    parser.add_argument(
        "--weights-wide", type=Path,
        default=CNN_DIR / "mobilenet_onchip_bf16_wide.mem",
        help="256-bit verification image containing four logical 64-bit rows",
    )
    for bank in range(4):
        parser.add_argument(
            f"--weights-bank{bank}", type=Path,
            default=CNN_DIR / f"mobilenet_onchip_bf16_bank{bank}.mem",
            help=f"64-bit synthesis BRAM image for interleaved bank {bank}",
        )
    parser.add_argument("--layers", type=Path, default=VMOD_DIR / "sigma_mobilenet_layers.vh")
    parser.add_argument("--manifest", type=Path, default=CNN_DIR / "mobilenet_onchip_manifest.json")
    args = parser.parse_args()

    if not args.checkpoint.is_file():
        raise SystemExit(
            f"Checkpoint not found: {args.checkpoint}\n"
            "Run cnn/train_mobilenet_onchip.py before packing."
        )
    model, checkpoint = load_checkpoint(args.checkpoint)
    ops = extract_affine_ops(model)
    words = []
    packed_wide_rows = []
    layers = []
    for index, op in enumerate(ops):
        # Every layer begins on a 256-bit ROM boundary.  Existing engines keep
        # addressing logical 64-bit rows, while the M=1/linear streamer can
        # fetch four consecutive rows at once without duplicating any weight.
        while len(packed_wide_rows) & 3:
            packed_wide_rows.append([0, 0, 0, 0])
        packed = packed_matrix(op)
        encoded = bf16_words(packed.reshape(-1))
        offset = len(words)
        words.extend(int(value) for value in encoded)
        in_c, _, _ = op.input_shape
        out_c, out_h, out_w = op.output_shape
        if op.kind == "linear":
            k_total = in_c + 1
        else:
            kernel = int(op.module.kernel_size[0])
            k_total = kernel * kernel * (1 if op.kind == "depthwise" else in_c) + 1

        layer_packed_offset = len(packed_wide_rows)
        if op.kind == "depthwise":
            # One BRAM row supplies the same kernel position for four adjacent
            # channels.  This is the natural access pattern of the four-lane
            # depthwise datapath.
            matrix = encoded.reshape(out_c, k_total)
            packed_layout = "depthwise-channel4"
            for channel_base in range(0, out_c, 4):
                for k_index in range(k_total):
                    packed_wide_rows.append([
                        int(matrix[channel_base + lane, k_index])
                        if channel_base + lane < out_c else 0
                        for lane in range(4)
                    ])
        elif (out_h * out_w == 1) and not op.residual:
            # The streamed M=1 engine evaluates four output channels in
            # parallel.  Keep four consecutive K rows together so one
            # physical 256-bit read supplies a complete four-PE fold.
            matrix = encoded.reshape(k_total, out_c)
            packed_layout = "m1-output4-k4"
            for output_base in range(0, out_c, 4):
                group_begin = len(packed_wide_rows)
                for k_index in range(k_total):
                    packed_wide_rows.append([
                        int(matrix[k_index, output_base + lane])
                        if output_base + lane < out_c else 0
                        for lane in range(4)
                    ])
                while (len(packed_wide_rows) - group_begin) & 3:
                    packed_wide_rows.append([0, 0, 0, 0])
        else:
            # Generic 4x4 SIGMA path: all four physical PEs in a DPE receive
            # one consecutive K fold in the same clock.
            matrix = encoded.reshape(k_total, out_c)
            packed_layout = "generic-k4"
            for output_index in range(out_c):
                for k_base in range(0, k_total, 4):
                    packed_wide_rows.append([
                        int(matrix[k_base + lane, output_index])
                        if k_base + lane < k_total else 0
                        for lane in range(4)
                    ])
        layers.append(layer_metadata(
            index, op, offset, len(encoded), layer_packed_offset,
            len(packed_wide_rows) - layer_packed_offset, packed_layout,
        ))

    args.weights.parent.mkdir(parents=True, exist_ok=True)
    args.weights_wide.parent.mkdir(parents=True, exist_ok=True)
    weight_bank_paths = [getattr(args, f"weights_bank{bank}") for bank in range(4)]
    for path in weight_bank_paths:
        path.parent.mkdir(parents=True, exist_ok=True)
    args.layers.parent.mkdir(parents=True, exist_ok=True)
    args.weights.write_text("".join(f"{value:04x}\n" for value in words), encoding="ascii")
    logical_wide_lines = []
    for row in packed_wide_rows:
        # $readmemh maps the right-most hex digits to bits [15:0].
        # Keep lane 0 in bits [15:0].
        logical_wide_lines.append("".join(
            f"{row[lane]:04x}" for lane in (3, 2, 1, 0)
        ))
    while len(logical_wide_lines) & 3:
        logical_wide_lines.append("0" * 16)
    # One physical 256-bit BRAM row contains four logical 64-bit rows.  The
    # right-most digits map to bits [63:0], so logical row 0 is emitted last.
    wide_lines = [
        "".join(reversed(logical_wide_lines[index:index + 4]))
        for index in range(0, len(logical_wide_lines), 4)
    ]
    args.weights_wide.write_text("\n".join(wide_lines) + "\n", encoding="ascii")
    # A 256-bit inferred ROM is wider than one UltraScale+ BRAM port.  Vivado
    # 2025.1 flattened it into LUT muxes instead of splitting the width.  Emit
    # the four physical 64-bit lanes explicitly so each array matches a native
    # BRAM template; an aligned read still returns all 256 bits in one cycle.
    weight_bank_lines = [logical_wide_lines[bank::4] for bank in range(4)]
    for path, bank_lines in zip(weight_bank_paths, weight_bank_lines):
        path.write_text("\n".join(bank_lines) + "\n", encoding="ascii")
    emit_verilog_case(layers, args.layers)
    manifest = {
        "network": "MobileNetV2-0.25 MNIST",
        "topology_source": "torchvision.models.mobilenet_v2",
        "checkpoint": str(args.checkpoint.resolve()),
        "training_clean_accuracy": checkpoint.get("clean_accuracy") if isinstance(checkpoint, dict) else None,
        "format": "BF16 BatchNorm-folded augmented GEMM matrices",
        "rtl_weight_layout": "256-bit physical rows containing four aligned 64-bit K4/output4/channel4 rows",
        "input": {"shape": [1, 28, 28], "layout": "HWC in activation bank 0"},
        "classes": list(range(10)),
        "weight_words": len(words),
        "weight_bytes": len(words) * 2,
        "weight_wide_words": len(logical_wide_lines),
        "weight_physical_rows": len(wide_lines),
        "weight_wide_bits": 256,
        "weight_bram_banks": 4,
        "weight_bank_width_bits": 64,
        "weight_bank_rows": len(wide_lines),
        "weight_bank_files": [path.name for path in weight_bank_paths],
        "activation_bank_words": 12288,
        "external_ddr_required": False,
        "affine_layers": len(layers),
        "layers": layers,
    }
    args.manifest.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"layers={len(layers)}")
    print(f"weights={args.weights.resolve()} words={len(words)} bytes={len(words) * 2}")
    print(f"weights_wide={args.weights_wide.resolve()} physical_rows={len(wide_lines)} logical64_rows={len(logical_wide_lines)}")
    print("weight_banks=" + ",".join(str(path.resolve()) for path in weight_bank_paths) +
          f" rows_per_bank={len(wide_lines)} width=64")
    print(f"metadata={args.layers.resolve()}")
    print(f"manifest={args.manifest.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
